[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  VITE_ENV = "production"

[dev]
  command = "npm run dev"
  targetPort = 5173
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[headers]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
      Access-Control-Allow-Methods = "GET,HEAD,PUT,PATCH,POST,DELETE"
      Access-Control-Allow-Headers = "Content-Type, Authorization"
